// <auto-generated />
namespace DnDCampaignAssistant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class databasepreliminarilycreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databasepreliminarilycreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201807162311355_database preliminarily created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
